# -*- coding: utf-8 -*-
#
# Copyright (C) 2025 alpLab (alplabai)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""
Touchstone (.snp) file writer for openEMS S-parameter export.

Implements Touchstone 1.0 format (EIA/IBIS Open Forum, compatible with
all major EDA tools).

Usage::

    from openEMS.touchstone import write_touchstone, ports_to_touchstone

    # From raw S-parameter data
    write_touchstone('output.s2p', freq, S, ref_impedance=50)

    # From openEMS port objects (after CalcPort)
    ports_to_touchstone(ports, 'output.s2p', freq, ref_impedance=50)
"""

import numpy as np
import os

_FREQ_UNITS = {
    'HZ':  1.0,
    'KHZ': 1e3,
    'MHZ': 1e6,
    'GHZ': 1e9,
}

_VALID_PARAMETERS = ('S', 'Y', 'Z', 'H', 'G')
_VALID_FORMATS = ('RI', 'MA', 'DB')


def _format_value_pair(value, format_type):
    """Convert a complex value to a pair of floats per the specified format.

    Parameters
    ----------
    value : complex
    format_type : str -- 'RI', 'MA', or 'DB'

    Returns
    -------
    (float, float)
    """
    if format_type == 'RI':
        return value.real, value.imag
    elif format_type == 'MA':
        return abs(value), np.degrees(np.angle(value))
    elif format_type == 'DB':
        mag_db = 20.0 * np.log10(max(abs(value), 1e-30))
        return mag_db, np.degrees(np.angle(value))
    else:
        raise ValueError(f"Unknown format type: {format_type}")


def write_touchstone(filename, freq, S, ref_impedance=50.0,
                     freq_unit='GHZ', parameter='S', format_type='RI',
                     comments=None):
    """Write S-parameters to a Touchstone 1.0 (.snp) file.

    Parameters
    ----------
    filename : str
        Output file path. Extension should match port count (.s1p, .s2p, etc.)
    freq : array_like, shape (N,)
        Frequency points in Hz.
    S : array_like, shape (n_ports, n_ports, N)
        Complex S-parameter matrix.
    ref_impedance : float
        Reference impedance in Ohms (default 50).
    freq_unit : str
        Frequency unit for the file: 'HZ', 'KHZ', 'MHZ', or 'GHZ'.
    parameter : str
        Network parameter type: 'S', 'Y', 'Z', 'H', or 'G'.
    format_type : str
        Data format: 'RI' (real/imag), 'MA' (magnitude/angle), or 'DB' (dB/angle).
    comments : list of str, optional
        Comment lines to include at the top of the file.
    """
    freq = np.asarray(freq, dtype=float)
    S = np.asarray(S, dtype=complex)

    if S.ndim != 3:
        raise ValueError(f"S must be 3D array (n_ports, n_ports, n_freq), got shape {S.shape}")

    n_ports = S.shape[0]
    if S.shape[1] != n_ports:
        raise ValueError(f"S must be square in first two dims, got {S.shape[0]}x{S.shape[1]}")
    if S.shape[2] != len(freq):
        raise ValueError(f"S freq dim ({S.shape[2]}) doesn't match freq length ({len(freq)})")

    freq_unit = freq_unit.upper()
    parameter = parameter.upper()
    format_type = format_type.upper()

    if freq_unit not in _FREQ_UNITS:
        raise ValueError(f"freq_unit must be one of {list(_FREQ_UNITS.keys())}")
    if parameter not in _VALID_PARAMETERS:
        raise ValueError(f"parameter must be one of {list(_VALID_PARAMETERS)}")
    if format_type not in _VALID_FORMATS:
        raise ValueError(f"format_type must be one of {list(_VALID_FORMATS)}")

    freq_scale = _FREQ_UNITS[freq_unit]

    with open(filename, 'w') as f:
        # Comment header
        f.write('! Touchstone file generated by openEMS (alpLab fork)\n')
        f.write(f'! Ports: {n_ports}\n')
        f.write(f'! Frequency points: {len(freq)}\n')
        if comments:
            for c in comments:
                f.write(f'! {c}\n')

        # Option line
        f.write(f'# {freq_unit} {parameter} {format_type} R {ref_impedance:.1f}\n')

        # Data
        for fi in range(len(freq)):
            f_scaled = freq[fi] / freq_scale

            if n_ports == 1:
                # 1-port: freq S11_a S11_b
                a, b = _format_value_pair(S[0, 0, fi], format_type)
                f.write(f'{f_scaled:.9e}  {a:.9e}  {b:.9e}\n')

            elif n_ports == 2:
                # 2-port: freq S11 S21 S12 S22 (note: column-major order per spec)
                pairs = []
                for row, col in [(0, 0), (1, 0), (0, 1), (1, 1)]:
                    a, b = _format_value_pair(S[row, col, fi], format_type)
                    pairs.extend([a, b])
                f.write(f'{f_scaled:.9e}')
                for v in pairs:
                    f.write(f'  {v:.9e}')
                f.write('\n')

            else:
                # N-port (N>=3): row-major, 4 pairs per line
                # First line starts with frequency
                pair_count = 0
                f.write(f'{f_scaled:.9e}')
                for row in range(n_ports):
                    for col in range(n_ports):
                        a, b = _format_value_pair(S[row, col, fi], format_type)
                        f.write(f'  {a:.9e}  {b:.9e}')
                        pair_count += 1
                        if pair_count % 4 == 0 and not (row == n_ports - 1 and col == n_ports - 1):
                            f.write('\n                      ')
                f.write('\n')


def read_touchstone(filename):
    """Read a Touchstone 1.0 file and return freq, S-matrix, and metadata.

    Parameters
    ----------
    filename : str
        Path to .snp file.

    Returns
    -------
    freq : ndarray, shape (N,)
        Frequency points in Hz.
    S : ndarray, shape (n_ports, n_ports, N)
        Complex S-parameter matrix.
    ref_impedance : float
        Reference impedance.
    """
    # Determine port count from extension
    ext = os.path.splitext(filename)[1].lower()
    if ext.startswith('.s') and ext.endswith('p'):
        n_ports = int(ext[2:-1])
    else:
        raise ValueError(f"Cannot determine port count from extension: {ext}")

    freq_scale = 1e9  # default GHz
    format_type = 'MA'
    ref_impedance = 50.0

    data_lines = []
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('!'):
                continue
            if line.startswith('#'):
                # Parse option line
                parts = line[1:].upper().split()
                idx = 0
                while idx < len(parts):
                    token = parts[idx]
                    if token in _FREQ_UNITS:
                        freq_scale = _FREQ_UNITS[token]
                    elif token in _VALID_PARAMETERS:
                        pass  # parameter type
                    elif token in _VALID_FORMATS:
                        format_type = token
                    elif token == 'R' and idx + 1 < len(parts):
                        idx += 1
                        ref_impedance = float(parts[idx])
                    idx += 1
                continue
            data_lines.append(line)

    # Parse all numeric values
    all_values = []
    for line in data_lines:
        vals = line.split()
        all_values.extend([float(v) for v in vals])

    # Each frequency point: 1 freq + n_ports*n_ports*2 values
    values_per_freq = 1 + 2 * n_ports * n_ports
    n_freq = len(all_values) // values_per_freq

    freq = np.zeros(n_freq)
    S = np.zeros((n_ports, n_ports, n_freq), dtype=complex)

    for fi in range(n_freq):
        offset = fi * values_per_freq
        freq[fi] = all_values[offset] * freq_scale

        vi = offset + 1
        if n_ports == 2:
            # 2-port order: S11 S21 S12 S22
            order = [(0, 0), (1, 0), (0, 1), (1, 1)]
        else:
            # Row-major for 1-port and N-port
            order = [(r, c) for r in range(n_ports) for c in range(n_ports)]

        for row, col in order:
            a, b = all_values[vi], all_values[vi + 1]
            vi += 2
            if format_type == 'RI':
                S[row, col, fi] = complex(a, b)
            elif format_type == 'MA':
                S[row, col, fi] = a * np.exp(1j * np.radians(b))
            elif format_type == 'DB':
                S[row, col, fi] = 10.0 ** (a / 20.0) * np.exp(1j * np.radians(b))

    return freq, S, ref_impedance


def ports_to_touchstone(ports, filename, freq, ref_impedance=50.0, **kwargs):
    """Extract S-matrix from openEMS Port objects and write Touchstone file.

    All ports must have had CalcPort() called already. This function assumes
    a single-excitation simulation where port[0] is the excited port.

    For multi-excitation S-matrix extraction, run multiple simulations
    (one per port excitation) and construct the S-matrix manually.

    Parameters
    ----------
    ports : list of Port
        List of port objects with CalcPort() already called.
    filename : str
        Output .snp file path.
    freq : array_like
        Frequency points in Hz (must match the freq used in CalcPort).
    ref_impedance : float
        Reference impedance (default 50 Ohms).
    **kwargs
        Additional arguments passed to write_touchstone().
    """
    n_ports = len(ports)
    n_freq = len(freq)

    S = np.zeros((n_ports, n_ports, n_freq), dtype=complex)

    # In a single-excitation setup, port[0] is excited
    # S[i][0] = port[i].uf_ref / port[0].uf_inc for all i
    exc_port = 0
    for p in range(n_ports):
        if hasattr(ports[p], 'uf_inc') and ports[p].uf_inc is not None:
            inc = ports[p].uf_inc
            if np.any(np.abs(inc) > 0):
                exc_port = p
                break

    for i in range(n_ports):
        S[i, exc_port, :] = ports[i].uf_ref / ports[exc_port].uf_inc

    write_touchstone(filename, freq, S, ref_impedance=ref_impedance, **kwargs)
